# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.",
#         "answer": "False"},
#     {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"}
# ]


question_data = [
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
        "question": "A group of islands is called an archipelago.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
        "question": "The music video to The Buggle's 'Video Killed the Radio Star'; was the first music video to broadcast on MTV.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
        "question": "Steel is an alloy of Iron and Carbon.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
        "question": "'I disapprove of what you say, but I will defend to the death your right to say it.'; is a quote from French philosopher Voltaire.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
        "question": "The longest place named in the United States is Lake Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Art", "type": "boolean", "difficulty": "medium",
        "question": "Vincent van Gogh cut off one of his ears.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
        "question": "Big the Cat is a playable character in 'Sonic Generations'.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Bulls are attracted to the color red.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
        "question": "In 'Team Fortress 2', the 'Bill's Hat'; is a reference to the game 'Dota 2'.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
        "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game's plot.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
        "question": "Samuel L. Jackson had the words, 'Bad Motherf*cker'; in-scripted on his lightsaber during the filming of Star Wars.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
        "question": "'HTML' stands for Hypertext Markup Language.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
        "question": "EDM label Monstercat signs tracks instead of artists.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
        "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
        "question": "In Pokemon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
        "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
        "question": "All of these maps were in 'Tom Clancy's Rainbow Six Siege' on its initial release: House, Clubhouse, Border, Consulate.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
        "question": "Tupac Shakur died due to complications from being stabbed in 1996.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
        "question": "The Fiat Multipla is a drivable car in 'Forza Horizon 3'.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
        "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.", "correct_answer": "True", "incorrect_answers": ["False"]}
]
